name: Python test

on:
  pull_request:
    types: [reopened]
# Disable this so it doesn't run on every push to this branch; revert before actually merging :)

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            asset: ozy-linux
          - os: macos-12
            asset: ozy-osx

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Deps
        run: make deps
      - name: Test and check dist
        run: make test dist
      - name: Ensure it runs
        run: dist/ozy --version
