name: Rust CI

on: push

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            asset: ozy-Linux-x86_64
            runs-on: ubuntu-22.04
          - target: x86_64-apple-darwin
            asset: ozy-Darwin-x86_64
            runs-on: macos-12

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Format
        run: cargo fmt
      - name: Clippy
        run: cargo clippy
      - if: ${{ contains(matrix.target, '-musl') }}
        run: sudo apt-get install musl-tools
      - name: Test
        run: cargo test --target=${{ matrix.target }}
