name: Python test

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            asset: ozy-linux
          - os: macos-10.15
            asset: ozy-osx

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Deps
        run: make deps
      - name: Test and check dist
        run: make test dist
