name: Python test

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            asset: ozy-linux
          - os: macos-10.15
            asset: ozy-osx

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Deps
        run: make deps
      - name: Test
        run: make test
      - name: Build dist
        run: make dist OUTPUT_NAME=${{ matrix.asset }}
      - name: Make a latest release
        #if: github.ref == 'refs/heads/main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest prerelease build"
          files: dist/${{ matrix.asset }}
