name: Create Rust release

on:
  push:
    tags:
      - 'v0.1.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            asset: ozy-Linux-x86_64

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - if: ${{ contains(matrix.target, '-musl') }}
        run: sudo apt-get install musl-tools
      - name: Build
        run: cargo build --release --verbose --target=${{ matrix.target }} --manifest-path rozy/Cargo.toml
      - name: Rename
        run: mv rozy/target/${{ matrix.target }}/release/ozy rozy/target/${{ matrix.target }}/release/${{ matrix.asset }}
      - name: Upload binaries to release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: rozy/target/${{ matrix.target }}/release/${{ matrix.asset }}
