name: Create python release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            asset: ozy-linux
          - os: macos-10.15
            asset: ozy-osx

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Deps
        run: make deps
      - name: Test
        run: make test
      - name: Dist
        run: make dist OUTPUT_NAME=${{ matrix.asset }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.asset }}
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
          prerelease: true
          overwrite: true
          body: "An ozy release which needs to be updated"
