name: Create python release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            asset: ozy-linux
          - os: macos-10.15
            asset: ozy-osx

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Deps
        run: make deps
      - name: Test
        run: make test
      - name: Dist
        run: make dist OUTPUT_NAME=${{ matrix.asset }}
      - name: Ensure version is correct
        run: dist/${{ matrix.asset }} --version | grep "$(echo $GITHUB_REF | cut -d / -f 3)"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset }}
          path: dist/${{ matrix.asset }}

  upload:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Upload binaries to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: *
